modLoader = "javafml"
loaderVersion = "${loader_version_range}"
license = "${mod_license}"
issueTrackerURL = "https://github.com/redstoneguy10ls/lithiccoins/issues"

[[mods]]
    modId = "${mod_id}"
    version = "${mod_version}"
    displayName = "${mod_name}"
    credits = "${mod_credits}"
    authors = "${mod_authors}"
    description='''${mod_description}'''

[[dependencies.${mod_id}]]
    modId = "neoforge"
    type = "required"
    versionRange = "[${neo_version},)"
    ordering = "NONE"
    side = "BOTH"

[[dependencies.${mod_id}]]
    modId = "minecraft"
    type = "required"
    versionRange = "${minecraft_version_range}"
    ordering = "NONE"
    side = "BOTH"

[[dependencies.${mod_id}]]
    modId = "tfc"
    mandatory = true
    versionRange = "[1.21.1-4.0.18,)"
    ordering = "AFTER"
    side = "BOTH"

[[dependencies.${mod_id}]]
    modId = "firmalife"
    mandatory = true
    versionRange = "[3.0.3,)"
    ordering = "AFTER"
    side = "BOTH"

[[dependencies.${mod_id}]]
    modId = "tfc_ie_addon"
    mandatory = false
    versionRange = "[2.1.0,)"
    ordering = "AFTER"
    side = "BOTH"
